package io.github.aishwaryajayanth1820.tds.ddl;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.Test;

import io.github.aishwaryajayanth1820.tds.ddl.MigrationPlan.StepClass;
import io.github.aishwaryajayanth1820.tds.grammar.Model.Template;
import io.github.aishwaryajayanth1820.tds.grammar.StructuralValidator;
import io.github.aishwaryajayanth1820.tds.grammar.TemplateParser;
import io.github.aishwaryajayanth1820.tds.jdbc.DbVendor;

import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;

/** DDL per dialect (grammar §4.1) and change classification (ADR-0013). */
class DdlAndPlannerTest {

    private static final JsonMapper MAPPER = JsonMapper.builder().build();
    private final TemplateParser parser = new TemplateParser(MAPPER, new StructuralValidator());
    private final DdlGenerator sqlite = new DdlGenerator(SqlDialect.of(DbVendor.SQLITE));
    private final DdlGenerator pg = new DdlGenerator(SqlDialect.of(DbVendor.POSTGRESQL));

    private ObjectNode json(String name) throws Exception {
        return (ObjectNode) MAPPER.readTree(Files.readString(Path.of("templates", name + ".json")));
    }

    private Template parse(ObjectNode doc) {
        var r = parser.parse(doc);
        assertThat(r.issues()).isEmpty();
        return r.template().orElseThrow();
    }

    @Test
    void sqliteDdlEncodesTypesConstraintsAndRules() throws Exception {
        String ddl = String.join(";\n", sqlite.createTable(parse(json("alerts"))));
        assertThat(ddl)
                .contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT")
                .contains("\"alert_name\" TEXT NOT NULL CHECK (length(\"alert_name\") <= 255 AND trim(\"alert_name\") <> '')")
                .contains("\"alert_type\" TEXT NOT NULL DEFAULT 'INFO' CHECK (\"alert_type\" IN ('CRITICAL', 'MAJOR', 'MINOR', 'INFO'))")
                .contains("\"alert_group\" INTEGER NOT NULL REFERENCES \"alert_groups\"(\"id\") ON DELETE RESTRICT")
                .contains("CONSTRAINT \"ck_alerts_ticket_needs_site\" CHECK (NOT (\"alert_ticket\" IS NOT NULL AND trim(\"alert_ticket\") <> '')")
                .contains("\"row_version\" INTEGER NOT NULL DEFAULT 0")
                .contains("CREATE INDEX \"ix_alerts_alert_group\" ON \"alerts\" (\"alert_group\")");
    }

    @Test
    void postgresDdlUsesNativeTypes() throws Exception {
        String ddl = String.join(";\n", pg.createTable(parse(json("alerts"))));
        assertThat(ddl)
                .contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                .contains("\"alert_date\" TIMESTAMPTZ NOT NULL DEFAULT now()")
                .contains("\"alert_name\" VARCHAR(255) NOT NULL CHECK (trim(\"alert_name\") <> '')")
                .contains("\"alert_group\" BIGINT NOT NULL REFERENCES");
        assertThat(String.join(";", pg.createTable(parse(json("operator_settings")))))
                .contains("CREATE UNIQUE INDEX \"ux_operator_jurisdiction\" ON \"operator_settings\" (\"operator_name\", \"jurisdictional_name\")");
    }

    @Test
    void plannerClassifiesChangesAndBuildsTheSqliteRebuild() throws Exception {
        Template before = parse(json("alerts"));
        ObjectNode after = json("alerts");
        ArrayNode fields = after.withArray("fields");
        ((ObjectNode) fields.get(6)).put("name", "site_code").put("renamedFrom", "alert_site");
        fields.remove(5);
        ((ArrayNode) fields.get(3).get("values")).add("VALUE_5");
        after.withArray("rules").removeAll();
        after.withObject("view").withArray("search").removeAll();

        MigrationPlan plan = new MigrationPlanner(sqlite).plan(before, parse(after));

        assertThat(plan.steps()).extracting(MigrationPlan.Step::cls)
                .contains(StepClass.SAFE, StepClass.DESTRUCTIVE, StepClass.METADATA);
        assertThat(plan.steps()).extracting(MigrationPlan.Step::description)
                .anyMatch(d -> d.contains("Rename column alert_site → site_code"))
                .anyMatch(d -> d.contains("Drop column alert_source"))
                .anyMatch(d -> d.contains("Add enum value(s) VALUE_5"));
        assertThat(plan.rebuild()).isTrue();
        assertThat(plan.statements()).anyMatch(s -> s.startsWith("CREATE TABLE \"alerts__new\""))
                .anyMatch(s -> s.contains("SELECT") && s.contains("\"alert_site\"") && !s.contains("\"alert_source\""))
                .contains("DROP TABLE \"alerts\"", "ALTER TABLE \"alerts__new\" RENAME TO \"alerts\"");
    }

    @Test
    void typeChangesAreBlockedAndRequiredWithoutDefaultIsPreChecked() throws Exception {
        Template before = parse(json("operator_settings"));
        ObjectNode after = json("operator_settings");
        ((ObjectNode) after.withArray("fields").get(3)).put("type", "string");
        after.withArray("fields").add(MAPPER.readTree("{\"name\":\"region\",\"type\":\"string\",\"required\":true}"));

        MigrationPlan plan = new MigrationPlanner(sqlite).plan(before, parse(after));

        assertThat(plan.hasBlocked()).isTrue();
        assertThat(plan.preChecks()).extracting(MigrationPlan.PreCheck::countSql).contains("SELECT COUNT(*) FROM \"operator_settings\"");
    }

    @Test
    void metadataOnlyChangesNeedNoSqlAndPostgresStructuralChangesWaitForM7() throws Exception {
        Template before = parse(json("operator_settings"));
        ObjectNode labelOnly = json("operator_settings");
        labelOnly.put("label", "Operator settings (renamed)");
        assertThat(new MigrationPlanner(sqlite).plan(before, parse(labelOnly)).statements()).isEmpty();

        ObjectNode structural = json("operator_settings");
        structural.withArray("fields").add(MAPPER.readTree("{\"name\":\"note\",\"type\":\"text\"}"));
        MigrationPlan pgPlan = new MigrationPlanner(pg).plan(before, parse(structural));
        assertThat(pgPlan.hasBlocked()).isTrue();
        assertThat(List.copyOf(pgPlan.statements())).isEmpty();
    }
}
