-- TDS system tables (architecture §6.1). Keep in step with db/migration/sqlite/V1__system.sql.

CREATE TABLE tds_user (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username             VARCHAR(100) NOT NULL UNIQUE CHECK (length(username) >= 1),
  password_hash        VARCHAR(200) NOT NULL,
  display_name         VARCHAR(200),
  enabled              BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tds_role (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(41) NOT NULL UNIQUE CHECK (length(name) >= 1),
  description VARCHAR(500),
  builtin     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tds_user_role (
  user_id BIGINT NOT NULL REFERENCES tds_user(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES tds_role(id) ON DELETE RESTRICT,
  PRIMARY KEY (user_id, role_id)
);
CREATE INDEX ix_tds_user_role_role ON tds_user_role (role_id);

CREATE TABLE tds_template (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(63) NOT NULL UNIQUE,
  manage_type       VARCHAR(20) NOT NULL CHECK (manage_type IN ('VIEW', 'MANAGE_VIEW', 'DATA_SOURCE')),
  draft_json        TEXT NOT NULL,
  draft_checksum    VARCHAR(64) NOT NULL,
  published_version INTEGER,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by        VARCHAR(100) NOT NULL
);

CREATE TABLE tds_template_version (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id   BIGINT NOT NULL REFERENCES tds_template(id) ON DELETE CASCADE,
  version       INTEGER NOT NULL CHECK (version > 0),
  template_json TEXT NOT NULL,
  checksum      VARCHAR(64) NOT NULL,
  plan_json     TEXT,
  applied_sql   TEXT,
  published_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_by  VARCHAR(100) NOT NULL,
  UNIQUE (template_id, version)
);

CREATE TABLE tds_action_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_name VARCHAR(63) NOT NULL,
  action_name   VARCHAR(63) NOT NULL,
  record_id     BIGINT,
  username      VARCHAR(100) NOT NULL,
  started_at    TIMESTAMPTZ NOT NULL,
  duration_ms   INTEGER NOT NULL,
  status        VARCHAR(10) NOT NULL CHECK (status IN ('OK', 'ERROR', 'TIMEOUT')),
  message       TEXT
);
CREATE INDEX ix_tds_action_log_started ON tds_action_log (started_at);

INSERT INTO tds_role (name, description, builtin) VALUES
  ('admin',  'Full access. Manages templates, roles and users.', TRUE),
  ('viewer', 'Default role held by every user.', TRUE);
