package io.github.aishwaryajayanth1820.tds.ddl;

import io.github.aishwaryajayanth1820.tds.grammar.FieldType;
import io.github.aishwaryajayanth1820.tds.grammar.Model.Field;
import io.github.aishwaryajayanth1820.tds.jdbc.DbVendor;

import tools.jackson.databind.JsonNode;

/** Logical → physical SQL per database engine (grammar §4.1, ADR-0004). */
public final class SqlDialect {

    private final DbVendor vendor;

    private SqlDialect(DbVendor vendor) {
        this.vendor = vendor;
    }

    public static SqlDialect of(DbVendor vendor) {
        return new SqlDialect(vendor);
    }

    public DbVendor vendor() {
        return vendor;
    }

    public boolean isSqlite() {
        return vendor == DbVendor.SQLITE;
    }

    public String columnType(Field f) {
        boolean pg = !isSqlite();
        return switch (f.type()) {
            case ID -> pg ? "BIGINT" : "INTEGER";
            case STRING -> pg ? "VARCHAR(" + f.stringLength() + ")" : "TEXT";
            case TEXT -> "TEXT";
            case INTEGER -> "INTEGER";
            case LONG -> pg ? "BIGINT" : "INTEGER";
            case DECIMAL -> pg ? "NUMERIC(" + nz(f.precision(), 18) + "," + nz(f.scale(), 2) + ")" : "NUMERIC";
            case DOUBLE -> pg ? "DOUBLE PRECISION" : "REAL";
            case BOOLEAN -> pg ? "BOOLEAN" : "INTEGER";
            case DATE -> pg ? "DATE" : "TEXT";
            case DATETIME -> pg ? "TIMESTAMPTZ" : "TEXT";
            case TIME -> pg ? "TIME" : "TEXT";
            case ENUM -> pg ? "VARCHAR(64)" : "TEXT";
            case REF -> pg ? "BIGINT" : "INTEGER";
            case JSON -> pg ? "JSONB" : "TEXT";
            case UUID -> pg ? "UUID" : "TEXT";
        };
    }

    public String idColumnDefinition() {
        return isSqlite() ? "INTEGER PRIMARY KEY AUTOINCREMENT" : "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    public String nowExpression() {
        return vendor.nowSql();
    }

    public String nowDefault() {
        return isSqlite() ? "(" + vendor.nowSql() + ")" : vendor.nowSql();
    }

    public String todayDefault() {
        return isSqlite() ? "(date('now'))" : "CURRENT_DATE";
    }

    public String literal(JsonNode v, Field f) {
        if (v.isBoolean()) {
            return isSqlite() ? (v.asBoolean() ? "1" : "0") : (v.asBoolean() ? "TRUE" : "FALSE");
        }
        if (v.isNumber() || (f != null && f.type().isNumeric())) {
            return v.isNumber() ? v.numberValue().toString() : String.valueOf(Double.parseDouble(v.asString()));
        }
        return quoteString(v.asString());
    }

    public static String quoteString(String s) {
        return "'" + s.replace("'", "''") + "'";
    }

    /** Engine-specific column checks: SQLite has no VARCHAR length, no BOOLEAN and no JSON type. */
    public java.util.List<String> engineChecks(Field f, String column) {
        if (!isSqlite()) {
            return java.util.List.of();
        }
        if (f.type() == FieldType.STRING) {
            return java.util.List.of("length(" + column + ") <= " + f.stringLength());
        }
        if (f.type() == FieldType.BOOLEAN) {
            return java.util.List.of(column + " IN (0, 1)");
        }
        if (f.type() == FieldType.JSON) {
            return java.util.List.of("json_valid(" + column + ")");
        }
        return java.util.List.of();
    }

    public String timestampType() {
        return isSqlite() ? "TEXT" : "TIMESTAMPTZ";
    }

    public String userType() {
        return isSqlite() ? "TEXT" : "VARCHAR(100)";
    }

    public String versionType() {
        return isSqlite() ? "INTEGER" : "BIGINT";
    }

    /** Case-insensitive LIKE. */
    public String likeOperator() {
        return isSqlite() ? "LIKE" : "ILIKE";
    }

    private static int nz(Integer v, int dflt) {
        return v != null ? v : dflt;
    }
}
